[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['dep-core/=lib/dep-core/src/','dep-sol/=lib/dep-sol/src/']
# See more config options https://github.com/foundry-rs/foundry/tree/master/config